name: TradePlus
version: ${project.version}
authors: [Trophonix, Protonull]
main: com.trophonix.tradeplus.TradePlusPlugin
api-version: "1.16"
commands:
  trade:
    description: Trade command
  tradeplus:
    description: TradePlus admin command
    permission: tradeplus.admin
permissions:
  tradeplus.admin:
    description: TradePlus admin permission
    default: op
    children:
      tradeplus.trade: true
  tradeplus.admin.silent:
    description: Silence admin trade notifications
    default: false
